# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#

default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: db
  
development:
  <<: *default
  database: kyutechapp
  username: root
  password: password
  
test:
  <<: *default
  database: kyutechapp
  username: root
  password: password

production:
  <<: *default
  database: db_production
  #username: user_production
  #password:
  #database: kyutechapp
  username: root
  password: yzjDIbkqnzi3nd0



