source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
    use_frameworks!
    pod 'Fabric'
    pod 'Crashlytics'

    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'RealmSwift'
    pod 'Google/Analytics'
   
    pod 'SVProgressHUD'
    pod 'PageMenu'
    pod 'TTTAttributedLabel'
    pod 'REFrostedViewController'

